/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jms;

import com.sun.jdi.connect.spi.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import static jms.DBConnection.con;
import java.sql.Statement; // Import PreparedStatement
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;


/**
 *
 * @author 91955
 */
public class front extends javax.swing.JFrame {

    /**
     * Creates new form front
     */
    public front() {
        initComponents();
        setDetailsToTable();
    }
    String name,phno,addr;
    int cid;
    DefaultTableModel model;
    public void setDetailsToTable(){
    
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cust", "root", "1234");
            Statement st = con.createStatement();
            var rs =  st.executeQuery("select * from customer");
           
           while(rs.next()){
               String cid = rs.getString("id");
               String name = rs.getString("name");
               String phno = rs.getString("phno");
               String addr = rs.getString("addr");
               
               Object[] obj = {cid,name,phno,addr};
               model = (DefaultTableModel) tbl_customer.getModel();
               model.addRow(obj);
           }
        }catch(Exception e){
            e.printStackTrace();
        }
}
    public void clearTable(){
      DefaultTableModel model = (DefaultTableModel) tbl_customer.getModel();
      model.setRowCount(0);
      }  
    public boolean addCustomer(){
          boolean isAdded = false;
          cid = Integer.parseInt(txt_id.getText());
          name =txt_name.getText(); 
          phno =txt_phno.getText(); 
          addr = txt_addr.getText(); 
          
          try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cust", "root", "1234");
            String sql = "insert into customer values(?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1,cid);
            pst.setString(2,name);
            pst.setString(3,phno);
            pst.setString(4,addr);
            
            int rowCount = pst.executeUpdate();
            if(rowCount>0){
                isAdded = true;
            }
            else{
                isAdded = false;
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    return isAdded;
}
     public boolean deleteDetails(){
          boolean isdeleted = false;
           cid = Integer.parseInt(txt_id.getText());
          try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cust", "root", "1234");
            String sql = "delete from customer where id =?";
             PreparedStatement pst = con.prepareStatement(sql);
             pst.setInt(1,cid);
             int rowCount = pst.executeUpdate();
            if(rowCount>0){
                isdeleted = true;
            }
            else{
                isdeleted = false;
            }
        }catch(Exception e){
            e.printStackTrace();
        }
          return isdeleted;
      }
 public boolean update(){
           boolean isUpdated = false;
       
          name =txt_name.getText(); 
          phno =txt_phno.getText(); 
          addr = txt_addr.getText(); 
          cid = Integer.parseInt(txt_id.getText());
          try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cust", "root", "1234");
            String sql = "update customer set name = ?,phno =?,addr=? where id =?";
            PreparedStatement pst = con.prepareStatement(sql);
            
            pst.setString(1,name);
            pst.setString(2,phno);
            pst.setString(3,addr);
            pst.setInt(4,cid);
            
            int rowCount = pst.executeUpdate();
            if(rowCount>0){
                isUpdated = true;
            }
            else{
                isUpdated = false;
            }
        }catch(Exception e){
            e.printStackTrace();
        }
          return isUpdated;
 }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_customer = new rojeru_san.complementos.RSTableMetro();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_id = new app.bolivia.swing.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_name = new app.bolivia.swing.JCTextField();
        txt_phno = new app.bolivia.swing.JCTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_addr = new app.bolivia.swing.JCTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Pho no", "Addr"
            }
        ));
        tbl_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_customerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_customer);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 10, 430, 400));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 160, 40));

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 160, 40));

        jButton2.setBackground(new java.awt.Color(255, 204, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 160, 40));

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NAME");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        txt_phno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phnoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_phno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PH No");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ADDR");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        txt_addr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addrActionPerformed(evt);
            }
        });
        jPanel1.add(txt_addr, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jButton5.setBackground(new java.awt.Color(255, 51, 51));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 145, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      if(deleteDetails() == true){
              JOptionPane.showMessageDialog(this,"Customer Details Deleted ");
              clearTable();
              setDetailsToTable();
        }
        else{
        JOptionPane.showMessageDialog(this,"failed");
    }    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_phnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phnoActionPerformed

    private void txt_addrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addrActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String phno = txt_phno.getText();
        if(phno.length()!=10){
             JOptionPane.showMessageDialog(this,"Invalid Phno");
             return;
        }
        
 String name = txt_name.getText(); // Fetching the name from the text field
try {
    Class.forName("com.mysql.jdbc.Driver");
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cust", "root", "1234");
    
    // Create a prepared statement
    PreparedStatement pst = con.prepareStatement("CREATE TABLE IF NOT EXISTS " + name + " (\n" +
        //"id int AUTO_INCREMENT,\n"+
        "daten DATE,\n" +
        "given VARCHAR(10),\n" +
        "receive VARCHAR(10) )");
        //"constraint pkp PRIMARY KEY (id),\n" +
       // "constraint fkp foreign key(id) references customer(id))");
    
    // Execute the query
    pst.executeUpdate();
    
     //Close the statement
    pst.close();
    
} catch (Exception e) {
    e.printStackTrace();
}

      
        if(addCustomer() == true){
              JOptionPane.showMessageDialog(this,"customer addedd");
              clearTable();
              setDetailsToTable();
        }
        else{
        JOptionPane.showMessageDialog(this,"failed");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbl_customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_customerMouseClicked
 int rowNo = tbl_customer.getSelectedRow();
        TableModel model = tbl_customer.getModel();
        
        txt_id.setText(model.getValueAt(rowNo, 0).toString());
        txt_name.setText(model.getValueAt(rowNo, 1).toString());
        txt_phno.setText(model.getValueAt(rowNo, 2).toString());
       txt_addr.setText(model.getValueAt(rowNo, 3).toString());
                // TODO add your handling code here:
        
    }//GEN-LAST:event_tbl_customerMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        top t = new top();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
               if(update() == true){
              JOptionPane.showMessageDialog(this,"Details updated");
              clearTable();
              setDetailsToTable();
        }
        else{
        JOptionPane.showMessageDialog(this,"failed");
    }  
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new front().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.complementos.RSTableMetro tbl_customer;
    private app.bolivia.swing.JCTextField txt_addr;
    private app.bolivia.swing.JCTextField txt_id;
    private app.bolivia.swing.JCTextField txt_name;
    private app.bolivia.swing.JCTextField txt_phno;
    // End of variables declaration//GEN-END:variables
}
