/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jms;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static jms.DBConnection.con;

/**
 *
 * @author 91955
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
     private String name;
    public home(String name) {
        initComponents();
        this.name = name ;
        setDetailsToTable(name);
        Calc(name);
    }
    public void Calc(String name) {
    try {
        Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cust", "root", "1234");
        String sql = "select sum(given) as g, sum(receive) as r from " + name;
        PreparedStatement pst = con.prepareStatement(sql);
        var rs = pst.executeQuery();

        if (rs.next()) {
            // Retrieve the sum values from the result set
            int givenSum = rs.getInt("g");
            int receiveSum = rs.getInt("r");
            
            // Set the sum values to the corresponding labels
            lbl_given.setText(String.valueOf(givenSum));
            lbl_receive.setText(String.valueOf(receiveSum));
        }

        // Close the resources
        rs.close();
        pst.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    int id;
    DefaultTableModel model;
    public void setDetailsToTable(String name){
    
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cust", "root", "1234");
            Statement st = con.createStatement();
            lbl_receive.setText(name);
             var rs = st.executeQuery("SELECT * FROM " + name);
           
           while(rs.next()){
               String date = rs.getString("daten");
               String given = rs.getString("given");
               String recieve = rs.getString("receive");
               
               Object[] obj = {date,given,recieve};
               model = (DefaultTableModel) tbl_specificcustomer.getModel();
               model.addRow(obj);
           }
        }catch(Exception e){
            e.printStackTrace();
        }
}
    public void clearTable(){
      DefaultTableModel model = (DefaultTableModel) tbl_specificcustomer.getModel();
      model.setRowCount(0);
      }  
    public boolean addTransaction(String name){
          boolean isAdded = false;
          //id = Integer.parseInt(txt_id.getText());
          Date uDate  = date.getDatoFecha();
          String given=txt_given.getText(); 
          String receive =txt_recieve.getText(); 
           long l1 = uDate.getTime();
            
             
            java.sql.Date sDate = new java.sql.Date(l1);
          
          try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cust", "root", "1234");
            String sql = "insert into "+name+" values(?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
           // pst.setInt(1,id);
            pst.setDate(1,sDate);
            pst.setString(2,given);
            pst.setString(3,receive);
            
            int rowCount = pst.executeUpdate();
            if(rowCount>0){
                isAdded = true;
            }
            else{
                isAdded = false;
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    return isAdded;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_specificcustomer = new rojeru_san.complementos.RSTableMetro();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        date = new rojeru_san.componentes.RSDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lbl_receive = new javax.swing.JLabel();
        txt_recieve = new app.bolivia.swing.JCTextField();
        txt_given = new app.bolivia.swing.JCTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lbl_name1 = new javax.swing.JLabel();
        lbl_given = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NAME");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 52, 64, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 100, 106));

        tbl_specificcustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date ", "Amt Given", "Amt Recieve"
            }
        ));
        jScrollPane1.setViewportView(tbl_specificcustomer);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 6, 480, 380));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Given");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 70, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 60, -1));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TOTAL AMT");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 150, -1));

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 120, 40));

        lbl_receive.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_receive.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lbl_receive, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 100, 20));
        jPanel1.add(txt_recieve, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));
        jPanel1.add(txt_given, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 51, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 139, 36));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Recieve");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 80, -1));
        jPanel1.add(lbl_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 170, 20));

        lbl_given.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_given.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lbl_given, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 100, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        top t = new top();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        if(addTransaction(name) == true){
            JOptionPane.showMessageDialog(this,"Transaction addedd");
            clearTable();
            setDetailsToTable(name);
        }
        else{
            JOptionPane.showMessageDialog(this,"failed");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home("name").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.componentes.RSDateChooser date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_given;
    private javax.swing.JLabel lbl_name1;
    private javax.swing.JLabel lbl_receive;
    private rojeru_san.complementos.RSTableMetro tbl_specificcustomer;
    private app.bolivia.swing.JCTextField txt_given;
    private app.bolivia.swing.JCTextField txt_recieve;
    // End of variables declaration//GEN-END:variables
}
